import type { Coupon } from "@/types"

export const coupons: Coupon[] = [
  {
    id: 1,
    code: "WELCOME50",
    description: "50% off your first order",
    discount: "50%",
    discountType: "percentage",
    discountValue: 50,
    minimumOrder: 30,
    validUntil: "2026-08-31",
    isUsed: false,
    maxUses: 1,
    usedCount: 0,
  },
  {
    id: 2,
    code: "FREEDEL",
    description: "Free delivery on orders above ₵40",
    discount: "Free delivery",
    discountType: "fixed",
    discountValue: 15,
    minimumOrder: 40,
    validUntil: "2026-07-06",
    isUsed: false,
    maxUses: 3,
    usedCount: 1,
  },
  {
    id: 3,
    code: "BURGERWEEK",
    description: "20% off all burger orders",
    discount: "20%",
    discountType: "percentage",
    discountValue: 20,
    minimumOrder: 25,
    validUntil: "2026-07-10",
    isUsed: false,
    maxUses: 5,
    usedCount: 2,
  },
  {
    id: 4,
    code: "BLITZ15",
    description: "₵15 off your next order",
    discount: "₵15",
    discountType: "fixed",
    discountValue: 15,
    minimumOrder: 50,
    validUntil: "2026-07-15",
    isUsed: true,
    maxUses: 1,
    usedCount: 1,
  },
  {
    id: 5,
    code: "WEEKEND10",
    description: "10% off weekend orders",
    discount: "10%",
    discountType: "percentage",
    discountValue: 10,
    minimumOrder: 20,
    validUntil: "2026-07-31",
    isUsed: false,
    maxUses: 10,
    usedCount: 3,
  },
]
