import type { Order } from "@/types"

export const orders: Order[] = [
  {
    id: 1001,
    restaurantId: 1,
    restaurantName: "Burger House",
    restaurantLogo:
      "https://images.unsplash.com/photo-1550547660-d9450f859349?w=100&h=100&fit=crop",
    items: [
      {
        name: "Double Beef Burger",
        quantity: 2,
        price: 75,
        addons: ["Extra Cheese"],
      },
      { name: "Loaded Fries", quantity: 1, price: 35, addons: [] },
    ],
    subtotal: 185,
    deliveryFee: 8,
    discount: 10,
    tip: 5,
    total: 188,
    status: "on_the_way",
    createdAt: "2026-07-03T14:30:00",
    estimatedDelivery: "2026-07-03T15:10:00",
    deliveryAddress: "23 Independence Ave, Accra",
    paymentMethod: "Mobile Money",
    courier: {
      name: "Kwame Mensah",
      phone: "+233 24 555 7890",
      avatar:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
      rating: 4.8,
      vehicle: "Motorcycle",
    },
    timeline: [
      {
        status: "pending",
        label: "Order Placed",
        time: "14:30",
        completed: true,
      },
      {
        status: "confirmed",
        label: "Order Confirmed",
        time: "14:32",
        completed: true,
      },
      {
        status: "preparing",
        label: "Preparing",
        time: "14:35",
        completed: true,
      },
      {
        status: "ready",
        label: "Ready for Pickup",
        time: "14:50",
        completed: true,
      },
      {
        status: "picked_up",
        label: "Picked Up",
        time: "14:55",
        completed: true,
      },
      {
        status: "on_the_way",
        label: "On The Way",
        time: "14:58",
        completed: true,
      },
      { status: "delivered", label: "Delivered", time: null, completed: false },
    ],
  },
  {
    id: 1002,
    restaurantId: 2,
    restaurantName: "Mama's Kitchen",
    restaurantLogo:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=100&h=100&fit=crop",
    items: [
      {
        name: "Jollof Rice & Chicken",
        quantity: 1,
        price: 60,
        addons: ["Plantain"],
      },
      { name: "Kelewele", quantity: 1, price: 20, addons: [] },
    ],
    subtotal: 90,
    deliveryFee: 5,
    discount: 0,
    tip: 3,
    total: 98,
    status: "delivered",
    createdAt: "2026-07-02T12:15:00",
    estimatedDelivery: "2026-07-02T12:55:00",
    deliveryAddress: "23 Independence Ave, Accra",
    paymentMethod: "Mobile Money",
    timeline: [
      {
        status: "pending",
        label: "Order Placed",
        time: "12:15",
        completed: true,
      },
      {
        status: "confirmed",
        label: "Order Confirmed",
        time: "12:17",
        completed: true,
      },
      {
        status: "preparing",
        label: "Preparing",
        time: "12:20",
        completed: true,
      },
      {
        status: "ready",
        label: "Ready for Pickup",
        time: "12:40",
        completed: true,
      },
      {
        status: "picked_up",
        label: "Picked Up",
        time: "12:42",
        completed: true,
      },
      {
        status: "on_the_way",
        label: "On The Way",
        time: "12:45",
        completed: true,
      },
      {
        status: "delivered",
        label: "Delivered",
        time: "12:52",
        completed: true,
      },
    ],
  },
  {
    id: 1003,
    restaurantId: 5,
    restaurantName: "Shawarma King",
    restaurantLogo:
      "https://images.unsplash.com/photo-1561651188-d207bbec4ec3?w=100&h=100&fit=crop",
    items: [
      {
        name: "Chicken Shawarma Wrap",
        quantity: 2,
        price: 45,
        addons: ["Extra Meat", "Cheese"],
      },
    ],
    subtotal: 140,
    deliveryFee: 6,
    discount: 15,
    tip: 0,
    total: 131,
    status: "preparing",
    createdAt: "2026-07-03T15:00:00",
    estimatedDelivery: "2026-07-03T15:30:00",
    deliveryAddress: "45 Cantonments Rd, Accra",
    paymentMethod: "Card",
    timeline: [
      {
        status: "pending",
        label: "Order Placed",
        time: "15:00",
        completed: true,
      },
      {
        status: "confirmed",
        label: "Order Confirmed",
        time: "15:02",
        completed: true,
      },
      {
        status: "preparing",
        label: "Preparing",
        time: "15:05",
        completed: true,
      },
      {
        status: "ready",
        label: "Ready for Pickup",
        time: null,
        completed: false,
      },
      { status: "picked_up", label: "Picked Up", time: null, completed: false },
      {
        status: "on_the_way",
        label: "On The Way",
        time: null,
        completed: false,
      },
      { status: "delivered", label: "Delivered", time: null, completed: false },
    ],
  },
  {
    id: 1004,
    restaurantId: 3,
    restaurantName: "Pizza Palace",
    restaurantLogo:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=100&h=100&fit=crop",
    items: [
      {
        name: "Pepperoni Supreme",
        quantity: 1,
        price: 95,
        addons: ["Stuffed Crust"],
      },
      { name: "Garlic Bread", quantity: 1, price: 25, addons: [] },
    ],
    subtotal: 135,
    deliveryFee: 10,
    discount: 0,
    tip: 5,
    total: 150,
    status: "delivered",
    createdAt: "2026-06-30T19:00:00",
    estimatedDelivery: "2026-06-30T19:45:00",
    deliveryAddress: "23 Independence Ave, Accra",
    paymentMethod: "Wallet",
    timeline: [
      {
        status: "pending",
        label: "Order Placed",
        time: "19:00",
        completed: true,
      },
      {
        status: "confirmed",
        label: "Order Confirmed",
        time: "19:03",
        completed: true,
      },
      {
        status: "preparing",
        label: "Preparing",
        time: "19:05",
        completed: true,
      },
      {
        status: "ready",
        label: "Ready for Pickup",
        time: "19:25",
        completed: true,
      },
      {
        status: "picked_up",
        label: "Picked Up",
        time: "19:28",
        completed: true,
      },
      {
        status: "on_the_way",
        label: "On The Way",
        time: "19:30",
        completed: true,
      },
      {
        status: "delivered",
        label: "Delivered",
        time: "19:42",
        completed: true,
      },
    ],
  },
  {
    id: 1005,
    restaurantId: 9,
    restaurantName: "Banku & Tilapia Spot",
    restaurantLogo:
      "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=100&h=100&fit=crop",
    items: [
      {
        name: "Banku & Grilled Tilapia",
        quantity: 1,
        price: 70,
        addons: ["Extra Pepper"],
      },
    ],
    subtotal: 75,
    deliveryFee: 6,
    discount: 0,
    tip: 5,
    total: 86,
    status: "cancelled",
    createdAt: "2026-06-28T13:00:00",
    estimatedDelivery: "2026-06-28T13:45:00",
    deliveryAddress: "12 Osu Badu St, Accra",
    paymentMethod: "Mobile Money",
    timeline: [
      {
        status: "pending",
        label: "Order Placed",
        time: "13:00",
        completed: true,
      },
      {
        status: "confirmed",
        label: "Order Confirmed",
        time: "13:02",
        completed: true,
      },
      {
        status: "cancelled",
        label: "Cancelled",
        time: "13:10",
        completed: true,
      },
      { status: "preparing", label: "Preparing", time: null, completed: false },
      {
        status: "ready",
        label: "Ready for Pickup",
        time: null,
        completed: false,
      },
      { status: "picked_up", label: "Picked Up", time: null, completed: false },
      {
        status: "on_the_way",
        label: "On The Way",
        time: null,
        completed: false,
      },
      { status: "delivered", label: "Delivered", time: null, completed: false },
    ],
  },
  {
    id: 1006,
    restaurantId: 99,
    restaurantName: "Mensah's Kitchen",
    restaurantLogo:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=100&h=100&fit=crop",
    items: [
      {
        name: "Jollof Rice & Chicken",
        quantity: 2,
        price: 60,
        addons: ["Plantain"],
      },
      { name: "Kelewele", quantity: 1, price: 20, addons: [] },
    ],
    subtotal: 160,
    deliveryFee: 5,
    discount: 10,
    tip: 4,
    total: 159,
    status: "on_the_way",
    createdAt: "2026-07-04T18:00:00",
    estimatedDelivery: "2026-07-04T18:35:00",
    deliveryAddress: "5 Cantonments Rd, Accra",
    paymentMethod: "Mobile Money",
    courier: {
      name: "Kojo Antwi",
      phone: "+233 24 111 2233",
      avatar:
        "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
      rating: 4.9,
      vehicle: "Motorcycle",
    },
    timeline: [
      {
        status: "pending",
        label: "Order Placed",
        time: "18:00",
        completed: true,
      },
      {
        status: "confirmed",
        label: "Order Confirmed",
        time: "18:02",
        completed: true,
      },
      {
        status: "preparing",
        label: "Preparing",
        time: "18:05",
        completed: true,
      },
      {
        status: "ready",
        label: "Ready for Pickup",
        time: "18:20",
        completed: true,
      },
      {
        status: "picked_up",
        label: "Picked Up",
        time: "18:22",
        completed: true,
      },
      {
        status: "on_the_way",
        label: "On The Way",
        time: "18:25",
        completed: true,
      },
      { status: "delivered", label: "Delivered", time: null, completed: false },
    ],
  },
  {
    id: 1007,
    restaurantId: 99,
    restaurantName: "Mensah's Kitchen",
    restaurantLogo:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=100&h=100&fit=crop",
    items: [
      {
        name: "Waakye Special",
        quantity: 1,
        price: 45,
        addons: ["Fish", "Egg"],
      },
      {
        name: "Jollof Rice & Chicken",
        quantity: 1,
        price: 60,
        addons: [],
      },
    ],
    subtotal: 105,
    deliveryFee: 5,
    discount: 0,
    tip: 3,
    total: 113,
    status: "delivered",
    createdAt: "2026-07-03T12:15:00",
    estimatedDelivery: "2026-07-03T12:50:00",
    deliveryAddress: "12 Osu Badu St, Accra",
    paymentMethod: "Card",
    timeline: [
      {
        status: "pending",
        label: "Order Placed",
        time: "12:15",
        completed: true,
      },
      {
        status: "confirmed",
        label: "Order Confirmed",
        time: "12:17",
        completed: true,
      },
      {
        status: "preparing",
        label: "Preparing",
        time: "12:20",
        completed: true,
      },
      {
        status: "ready",
        label: "Ready for Pickup",
        time: "12:40",
        completed: true,
      },
      {
        status: "picked_up",
        label: "Picked Up",
        time: "12:42",
        completed: true,
      },
      {
        status: "on_the_way",
        label: "On The Way",
        time: "12:45",
        completed: true,
      },
      {
        status: "delivered",
        label: "Delivered",
        time: "12:52",
        completed: true,
      },
    ],
  },
  {
    id: 1008,
    restaurantId: 99,
    restaurantName: "Mensah's Kitchen",
    restaurantLogo:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=100&h=100&fit=crop",
    items: [
      {
        name: "Fufu & Light Soup",
        quantity: 1,
        price: 55,
        addons: ["Extra Meat"],
      },
      {
        name: "Grilled Tilapia & Banku",
        quantity: 1,
        price: 70,
        addons: [],
      },
    ],
    subtotal: 145,
    deliveryFee: 5,
    discount: 0,
    tip: 5,
    total: 155,
    status: "preparing",
    createdAt: "2026-07-04T19:30:00",
    estimatedDelivery: "2026-07-04T20:05:00",
    deliveryAddress: "23 Independence Ave, Accra",
    paymentMethod: "Wallet",
    timeline: [
      {
        status: "pending",
        label: "Order Placed",
        time: "19:30",
        completed: true,
      },
      {
        status: "confirmed",
        label: "Order Confirmed",
        time: "19:32",
        completed: true,
      },
      {
        status: "preparing",
        label: "Preparing",
        time: "19:35",
        completed: true,
      },
      {
        status: "ready",
        label: "Ready for Pickup",
        time: null,
        completed: false,
      },
      { status: "picked_up", label: "Picked Up", time: null, completed: false },
      {
        status: "on_the_way",
        label: "On The Way",
        time: null,
        completed: false,
      },
      { status: "delivered", label: "Delivered", time: null, completed: false },
    ],
  },
]
